--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: hi-c.chr ; long font name: Helv_I

package Graph.F.Helv_I is
  pragma Elaborate_body;
  Helv_IFont: p_Vector_Font;
end Graph.F.Helv_I;
