--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: euro.chr ; long font name: EuroStyle

package Graph.F.EuroStyle is
  pragma Elaborate_body;
  EuroStyleFont: p_Vector_Font;
end Graph.F.EuroStyle;
