--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: goth.chr ; long font name: Gothic

package Graph.F.Gothic is
  pragma Elaborate_body;
  GothicFont: p_Vector_Font;
end Graph.F.Gothic;
