--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: bold.chr ; long font name: Bold

package Graph.F.Bold is
  pragma Elaborate_body;
  BoldFont: p_Vector_Font;
end Graph.F.Bold;
