--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: tscr.chr ; long font name: TriScript

package Graph.F.TriScript is
  pragma Elaborate_body;
  TriScriptFont: p_Vector_Font;
end Graph.F.TriScript;
