--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: hb-c.chr ; long font name: Helv_B

package Graph.F.Helv_B is
  pragma Elaborate_body;
  Helv_BFont: p_Vector_Font;
end Graph.F.Helv_B;
