--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: h--c.chr ; long font name: Helv

package Graph.F.Helv is
  pragma Elaborate_body;
  HelvFont: p_Vector_Font;
end Graph.F.Helv;
