--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: simp.chr ; long font name: Simple

package Graph.F.Simple is
  pragma Elaborate_body;
  SimpleFont: p_Vector_Font;
end Graph.F.Simple;
