--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: trip.chr ; long font name: Triplex

package Graph.F.Triplex is
  pragma Elaborate_body;
  TriplexFont: p_Vector_Font;
end Graph.F.Triplex;
