--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: litt.chr ; long font name: Small

package Graph.F.Small is
  pragma Elaborate_body;
  SmallFont: p_Vector_Font;
end Graph.F.Small;
