--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: sans.chr ; long font name: SansSerif

package Graph.F.SansSerif is
  pragma Elaborate_body;
  SansSerifFont: p_Vector_Font;
end Graph.F.SansSerif;
