--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: scri.chr ; long font name: Script

package Graph.F.Script is
  pragma Elaborate_body;
  ScriptFont: p_Vector_Font;
end Graph.F.Script;
