--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: hbic.chr ; long font name: Helv_BI

package Graph.F.Helv_BI is
  pragma Elaborate_body;
  Helv_BIFont: p_Vector_Font;
end Graph.F.Helv_BI;
