--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: nobl.chr ; long font name: Noble

package Graph.F.Noble is
  pragma Elaborate_body;
  NobleFont: p_Vector_Font;
end Graph.F.Noble;
