--< "Graph for Ada" font package, format: 12-Jul-2003 >--
--< File automatically generated by: chr2vect.pas     >--
--
-- Source CHR file: lcom.chr ; long font name: Complex

package Graph.F.Complex is
  pragma Elaborate_body;
  ComplexFont: p_Vector_Font;
end Graph.F.Complex;
